// AccountType enum
export enum AccountType {
  CUSTOMER = 'CUSTOMER',
  PROVIDER = 'PROVIDER'
}

// PaymentRule enum
export enum PaymentRule {
  DEFAULT = 'DEFAULT',
  FIRST_MONDAY = 'FIRST_MONDAY',
  FIRST_MON_NORFND = 'FIRST_MON_NORFND',
  FIRST_MON_CANCEL = 'FIRST_MON_CANCEL',
  FNIGHT_CHECKIN = 'FNIGHT_CHECKIN',
  FNIGHT_CHKIN_5 = 'FNIGHT_CHKIN_5',
  FNIGHT_CHKIN_10 = 'FNIGHT_CHKIN_10',
  FNIGHT_CHKIN_15 = 'FNIGHT_CHKIN_15',
  FNIGHT_CHKIN_5_NORFND = 'FNIGHT_CHKIN_5_NORFND',
  FNIGHT_CHKIN_10_NORFND = 'FNIGHT_CHKIN_10_NORFND',
  FNIGHT_CHKIN_15_NORFND = 'FNIGHT_CHKIN_15_NORFND',
  FNIGHT_CHKIN_0_NORFND = 'FNIGHT_CHKIN_0_NORFND',
  FNIGHT_AUTOCANCEL = 'FNIGHT_AUTOCANCEL',
  WEEK_CHECKIN_7 = 'WEEK_CHECKIN_7',
  WEEK_CHECKOUT = 'WEEK_CHECKOUT',
  TENS_CHECKIN_7 = 'TENS_CHECKIN_7',
  NEXT_MONTH = 'NEXT_MONTH',
  CANPOLICIES_7 = 'CANPOLICIES_7',
  CANPOLICIES_4 = 'CANPOLICIES_4',
  CANPOLICIES_3 = 'CANPOLICIES_3',
  CANPOLICIES_2 = 'CANPOLICIES_2',
  CANPOLICIES_1 = 'CANPOLICIES_1',
  AUTOCANCEL_7 = 'AUTOCANCEL_7',
  AUTOCANCEL_6 = 'AUTOCANCEL_6',
  AUTOCANCEL_5 = 'AUTOCANCEL_5',
  AUTOCANCEL_4 = 'AUTOCANCEL_4',
  AUTOCANCEL_3 = 'AUTOCANCEL_3',
  AUTOCANCEL_2 = 'AUTOCANCEL_2',
  AUTOCANCEL_1 = 'AUTOCANCEL_1',
  CHECKIN_PLUS_1 = 'CHECKIN_PLUS_1',
  CHECKIN_PLUS_2 = 'CHECKIN_PLUS_2',
  CHECKIN_PLUS_29 = 'CHECKIN_PLUS_29',
  CHECKIN_MINUS_1 = 'CHECKIN_MINUS_1',
  CHECKIN_MINUS_4 = 'CHECKIN_MINUS_4',
  CHECKIN_MINUS_7 = 'CHECKIN_MINUS_7',
  EVERY_10_DAYS = 'EVERY_10_DAYS'
}

// BookingStatus enum
export enum BookingStatus {
  CANCELLATION_PENDING = 'CANCELLATION_PENDING',
  CANCELLATION_FAILED = 'CANCELLATION_FAILED',
  CANCELLED = 'CANCELLED',
  CANCELLED_WITH_CHARGES = 'CANCELLED_WITH_CHARGES',
  CONFIRMATION_DENIED = 'CONFIRMATION_DENIED',
  CONFIRMATION_PENDING = 'CONFIRMATION_PENDING',
  CONFIRMED = 'CONFIRMED',
  MIXED = 'MIXED',
  REBOOKING = 'REBOOKING',
  REJECTED = 'REJECTED',
  REQUEST_FAILED = 'REQUEST_FAILED'
}

// FileCustomerStatus enum
export enum FileCustomerStatus {
  TO_ACCOUNT = 'TO_ACCOUNT',
  CANCELLED = 'CANCELLED',
  AMOUNT_CHARGED = 'AMOUNT_CHARGED',
  END = 'END',
  INITIAL = 'INITIAL',
  INTERCOMPANY = 'INTERCOMPANY',
  INVOICED = 'INVOICED',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  PROFORMA_SENT = 'PROFORMA_SENT',
  PROFORMA_TO_SEND = 'PROFORMA_TO_SEND',
  REBILLING = 'REBILLING'
}

// FileProviderStatus enum
export enum FileProviderStatus {
  CANCELLED = 'CANCELLED',
  RECONFIRMED = 'RECONFIRMED',
  END = 'END',
  ERROR = 'ERROR',
  EXPIRED_VALIDATION = 'EXPIRED_VALIDATION',
  INITIAL = 'INITIAL',
  PAID = 'PAID',
  REBILLING = 'REBILLING',
  REQUEST_REFUND = 'REQUEST_REFUND',
  TO_VALIDATE = 'TO_VALIDATE',
  WHITELIST = 'WHITELIST'
}

// BookingHistoryAction enum
export enum BookingHistoryAction {
  CREATED = 'CREATED',
  UPDATED = 'UPDATED',
  FILE_INITIALIZED = 'FILE_INITIALIZED',
  FILE_STATUS_SYNCED = 'FILE_STATUS_SYNCED',
  CUSTOMER_STATUS_CHANGE = 'CUSTOMER_STATUS_CHANGE',
  PROVIDER_STATUS_CHANGE = 'PROVIDER_STATUS_CHANGE',
  FILE_CUSTOMER_REBILLING = 'FILE_CUSTOMER_REBILLING',
  FILE_CUSTOMER_TO_ACCOUNT = 'FILE_CUSTOMER_TO_ACCOUNT',
  FILE_CUSTOMER_INVOICED = 'FILE_CUSTOMER_INVOICED',
  FILE_PROVIDER_REQUEST_REFUND = 'FILE_PROVIDER_REQUEST_REFUND',
  AUTO_PAYMENT_PROCESSED = 'AUTO_PAYMENT_PROCESSED'
}
